---

# Dependencies specify other packages that your package needs in order to work.# For information on the generic Dart part of this file, see the  # An image asset can refer to one or more resolution-specific "variants", see  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # https://flutter.dev/assets-and-images/#resolution-aware

# following page: https://dart.dev/tools/pub/pubspec

dependencies:
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.8
  simple_gradient_text: ^1.3.0
  animations: ^2.0.1
  dart_jsonwebtoken: ^2.11.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.7
  edgar: ^0.3.1
  qr_flutter: ^4.1.0
  http: ^1.1.0
  path_provider: ^2.0.5
  flutter_pdfview: ^1.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter  
  bootstrap_icons: ^1.11.1
  auto_size_text: ^3.0.0
  aligned_dialog: ^0.0.7
  logger: ^2.0.2+1
  flutter_datetime_picker: ^1.5.1
  file_picker: ^8.0.0+1
  confetti: ^0.8.0
  flutter_typeahead: ^5.2.0
  easy_autocomplete: ^1.6.0
  web_socket_channel: ^3.0.1
  flutter_boring_avatars: ^2.0.1
  permission_handler: ^11.3.1
  download_file: ^1.2.0
  push: ^2.3.0
  flutter_native_splash: ^2.4.1
  provider: ^6.1.2
  gradient_borders: ^1.0.1
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: launcher_icon
  adaptive_icon_background: "#335FC2"
  adaptive_icon_foreground: "assets/images/logo/Launcher_icon.png"
  ios: true
  image_path: "assets/images/logo/Launcher_icon.png"
flutter_native_splash:
  color: "#335FC2"
  image: "assets/images/logo/Launcher_icon.png"
  android: true
  ios: true
  web: true
 

environment:
  sdk: '>=2.18.4 <3.0.0'
flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-Regular.ttf
        - asset: assets/font/Raleway-Medium.ttf
        - asset: assets/font/Raleway-Italic.ttf
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Regular.ttf
        - asset: assets/font/Poppins/Poppins-Medium.ttf
        - asset: assets/font/Poppins/Poppins-Italic.ttf
        - asset: assets/font/Poppins/Poppins-Bold.ttf
        - asset: assets/font/Poppins/Poppins-SemiBold.ttf
        - asset: assets/font/Poppins/Poppins-Light.ttf
        - asset: assets/font/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/font/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/font/Poppins/Poppins-Thin.ttf
        - asset: assets/font/Poppins/Poppins-Black.ttf
        - asset: assets/font/Poppins/Poppins-BlackItalic.ttf
  assets:
    - assets/images/logo/
    - assets/images/utils/
    - .env  # The following line ensures that the Material Icons font is
name: edgar_app
publish_to: none
version: 1.0.0+1
