name: Build and Deploy Flutter APK

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Java Environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: corretto

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_API_URL: ${{ secrets.API_URL }}
          envkey_APP_NAME: edgar.care
          directory: .
          file_name: .env
          fail_on_empty: false

      - name: Extract Branch Name
        run: echo branch=${GITHUB_REF#refs/heads/} >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Apk
        run: flutter build apk --release

      - name: Upload Apk to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk-${{ steps.extract_branch.outputs.branch }}
          path: build/app/outputs/apk/release/app-release.apk


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Apk
        uses: actions/download-artifact@v3
        with:
          name: apk-${{ needs.build.outputs.branch }}


      - name: Rename Production Apk
        if: ${{ needs.build.outputs.branch == 'main' }}
        run: mv ./app-release.apk ./edgar.care.apk

      - name: Rename Dev Apk
        if: ${{ needs.build.outputs.branch  != 'main' }}
        run: mv ./app-release.apk ./dev-edgar.care.apk

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Export Apk to S3
        run: aws s3 cp *.apk s3://${{ secrets.BUCKET_NAME }} --acl public-read
