name: Analyze Flutter Code

on:
  pull_request

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Java Environment"
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: corretto

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_API_URL: ${{ secrets.API_URL }}
          envkey_APP_NAME: edgar.care
          directory: .
          file_name: .env
          fail_on_empty: false

      - name: "Setup Flutter Environment"
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: "Analyze"
        run: flutter analyze
